image: maven:latest

stages:
  - build

build-project:
    stage: build
    script:
        - echo "Maven package start"
        - mvn clean install -U -e
        - echo "Maven package done"
    artifacts:
      paths:
        - "/target"