stages:
  - build
  - deploy

build-project:
  image: maven:latest
  stage: build
  script:
    - echo "Maven package start"
    - mvn install -DskipTests
    - mkdir app
    - cp target/Meeting-Application-0.0.1-SNAPSHOT.jar app/
    - echo "Maven package done"

deploy-to-ftp:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache curlftpfs
    - echo $FTP_PASSWORD | curlftpfs $FTP_USERNAME@$FTP_HOSTNAME ftp-mount -o password_stdin
    - cd ftp-mount
    - cp ../Meeting-Application-0.0.1-SNAPSHOT.jar ./Meeting-Application-0.0.1-SNAPSHOT.jar
    - cd ..
    - curl -u $FTP_USERNAME:$FTP_PASSWORD -T app/Meeting-Application-0.0.1-SNAPSHOT.jar ftp://$FTP_HOSTNAME/Meeting-Application-0.0.1-SNAPSHOT.jar
    - fusermount -u ftp-mount