image: maven-openjdk17-lftp

stages:
  - build

build-project:
    stage: build
    script:
        - echo "Maven package start"
        - mvn package
        - echo "Maven package done"
    artifacts:
      paths:
        - "/target"