stages:
  - build
  - deploy

build-project:
  image: maven:latest
  stage: build
  script:
    - echo "Maven package start"
    - mvn install -DskipTests
    - mkdir app
    - cp target/Meeting-Application-0.0.1-SNAPSHOT.jar app/
    - echo "Maven package done"

deploy-to-ftp:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache lftp
    - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOSTNAME; mirror -R app/Meeting-Application-0.0.1-SNAPSHOT.jar /"