stages:
  - build
  - deploy

build-project:
  image: maven:latest
  stage: build
  script:
    - echo "Maven package start"
    - mvn install -DskipTests
    - mkdir app
    - cp target/Meeting-Application-0.0.1-SNAPSHOT.jar app/
    - echo "Maven package done"

deploy-to-ftp:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache ftp
    - echo -e "user $FTP_USERNAME $FTP_PASSWORD\nput -R app/ /\nquit" | ftp -n $FTP_HOSTNAME
