image: maven:latest

stages:
  - build and deploy
  - deploy

build-project:
    stage: build and deploy
    image: alpine
    script:
        - apk add lftp
        - lftp --version
        - echo "Maven package start"
        - mvn install -D skipTests
        - echo "Maven package done"
        - cd /root/.m2/repository/com/jarema/lukasz/Meeting-Application/0.0.1-SNAPSHOT/
        - ls