stages:
  - build
  - deploy

build-project:
  image: maven:latest
  stage: build
  script:
    - echo "Maven package start"
    - mvn install -DskipTests
    - pwd
    - ls -l target/
    - mkdir app
    - cp target/Meeting-Application-0.0.1-SNAPSHOT.jar app/
    - echo "Maven package done"

deploy-to-ftp:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache ncftp pwd
    - ls app/
    - echo "put app/Meeting-Application-0.0.1-SNAPSHOT.jar /" | ncftp -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_HOSTNAME
