spring:
  mail:
    host: smtp.gmail.com
    username: meeting.application.pbs@gmail.com
    password: rjimggpxazrofcms
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true